name: Go

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: make

    - name: Test
      run: go test -v .

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset (darwin)
      id: upload-release-asset-darwin
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path:  ./dist/dio-exporter-darwin-amd64
        asset_name: dio-exporter-${{ env.RELEASE_VERSION }}-darwin-amd64
        asset_content_type: application/octet-stream

    - name: Upload Release Asset (linux)
      id: upload-release-asset-linux
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path:  ./dist/dio-exporter-linux-amd64
        asset_name: dio-exporter-${{ env.RELEASE_VERSION }}-linux-amd64
        asset_content_type: application/octet-stream

    - name: Upload Release Asset (windows)
      id: upload-release-asset-windows
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path:  ./dist/dio-exporter-windows-amd64.exe
        asset_name: dio-exporter-${{ env.RELEASE_VERSION }}-windows-amd64.exe
        asset_content_type: application/octet-stream
